# Generated by Django 4.1 on 2024-05-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bgm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgm', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bgm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('get_step', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('dir', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('name', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('task_id', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('man_uuid', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmallSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('link', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('background_music', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('download_progress', models.IntegerField(blank=True, null=True)),
                ('conversion_progress', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('data2', models.IntegerField(blank=True, null=True)),
                ('data3', models.FloatField(blank=True, null=True)),
                ('conversion_max', models.IntegerField(blank=True, null=True)),
                ('download_max', models.IntegerField(blank=True, null=True)),
                ('data4', models.DateTimeField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('add_back_progress', models.IntegerField(blank=True, null=True)),
                ('add_back_max', models.IntegerField(blank=True, null=True)),
                ('voice', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('background_music_id', models.IntegerField(blank=True, null=True)),
                ('voice_id', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'small_say',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('pass_field', models.TextField(blank=True, db_column='pass', null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voice',
                'managed': False,
            },
        ),
    ]
